### ISSUE TITLE
Line not displaying some character

### ISSUE THREAD

**Issue by HackerDeez** [jimeh/tmux-themepack#10]
Hey, i know its my side problem, but maybe you know the solution?

My tmux is not displaying U+E0E0, and all other arrows 

![2017-08-14-163921_1920x1080_scrot](https://user-images.githubusercontent.com/22556573/29274070-30148cce-810f-11e7-8816-71fa08829b2c.png)

there is my tmux.conf and the example of how the characters look

**Comment by jimeh** [comment]
Looks like you're not using a Powerline compatible font. This project has a bunch of common fonts modified for powerline: https://github.com/powerline/fonts
