### ISSUE TITLE
Cancel bottom margin of the status bar

### ISSUE THREAD

**Issue by sefechit** [jimeh/tmux-themepack#35]
Hello,
As you can see in the image attached, the status bar has a bottom margin. Is there a way to fix this?

Thank you in advance, love that theme btw <3

<img width="1440" alt="Screen Shot 2020-01-20 at 16 25 35" src="https://user-images.githubusercontent.com/44240685/72734072-be7f2b00-3ba1-11ea-8b62-a8b1a9204bde.png">

**Comment by jimeh** [comment]
As far as I'm aware, that margin has nothing to do with the theme, or even Tmux. I'm pretty sure it's simply that the height of your terminal doesn't perfectly fit the number of rows of text, so it makes the Terminal app/emulator place margins around it.

You can experiment with resizing the height of the terminal window up/down, and also tweaking the font size you're using using up/down a bit, and you should see the margin changing as you're doing that.

I hope that helps. I'll leave this issue open for now in case I can help any more with this :)

**Comment by sefechit** [comment]
it's a weird problem though but it doesn't have anything to do with you anyway.
In any case, thank you very much man <3
