### ISSUE TITLE
How to configure status

### ISSUE THREAD

**Issue by AxewBoTX** [jimeh/tmux-themepack#51]
I want to remove some things from the status bar and edit somethings too.
I want to completely remove the right status.
Also, I want to add a little windows or ubuntu icon to the extreme left of my status.
How can i do that?

**Comment by AxewBoTX** [comment]
also like how can I add a ubuntu or windows icon to left status?

**Comment by liiil825** [comment]
That's what i need

I want to modify date format and `pane` name is not changed then I run command `select-pane -T NewName`

**Comment by mflorin** [comment]
@liiil825 @AxewBoTX - I think it suffices to set `@themepack-status-right-area-left-format` , `...-area-middle-format` and `...area-right-format` like so:
```

set -goq @themepack-status-right-area-left-format "leftmost string on the right side"
set -goq @themepack-status-right-area-middle-format "middle string on the right side"
set -goq @themepack-status-right-area-right-format "rightmost string on the right side"
```

For example here's how I've replaced the rightmost side with git info:

```
set -g @themepack 'powerline/default/cyan'
set -goq @themepack-status-right-area-right-format '#(gitmux "#{pane_current_path}")'
...
run '~/.tmux/plugins/tpm/tpm'
```
