### ISSUE TITLE
How do you set basic theme?

### ISSUE THREAD

**Issue by Swoorup** [jimeh/tmux-themepack#6]

**Comment by jimeh** [comment]
Just specify the theme file you want in your tmux config via the `source-file` command.

**Comment by Swoorup** [comment]
@jimeh This seems not possible with tpm set command?

**Comment by jimeh** [comment]
Damn, you are right, the tmp setup only allows using the powerline themes. I'll fix it later today when I have time.

**Comment by m4tta** [comment]
Were you able to fix the issue of being able to use the default, non-powerline themes?

**Comment by jimeh** [comment]
Commit 027009b18b61323fbf4e06c39c15da30595bb5b6 should fix this. Apologies it took me so long to get around to.
