### ISSUE TITLE
Block tmux reattach theming failure

### ISSUE THREAD

**Issue by tommydrum** [jimeh/tmux-themepack#8]
This is probably an edge-case, but mind looking into it for me?
tmux 1.8 (rhel 7)
SSH through Putty (using Source Code for Powerline font with Solarized Dark theme color scheme)
After deattaching tmux session (c-b d), and reattaching that same session, tmux is failing to theme the block and status bar.

If you need/want more info, feel free to ping me.

**Comment by tommydrum** [comment]
Using tmux-themepack/powerline/block/blue.tmuxtheme if that's relevant at all.

**Comment by tommydrum** [comment]
My own config's fault. sorry.

**Comment by jimeh** [comment]
No worries :)
