### ISSUE TITLE
Suggestion: Highlight on pressing prefix.

### ISSUE THREAD

**Issue by PezCoder** [jimeh/tmux-themepack#9]
**Thank You**
First off, the themes are just lovely ❤️, been using it for a while now & it fits well with my vim's oceanic-next theme. 

**Suggestion**
Can we highlighting this part:
<img width="80" alt="screen shot 2017-08-13 at 6 59 54 pm" src="https://user-images.githubusercontent.com/8057916/29250083-a55367b4-8059-11e7-8061-e773f39cbec6.png">
on pressing of prefix key by either giving it more/less contrast would be really handy in determining the state of tmux.

**Comment by jimeh** [comment]
Not a bad idea. I'm not quite sure how or even if that's possible though. If you know please, feel free to submit a PR, otherwise I'll take a stab at it at some point when I have time :)

**Comment by PezCoder** [comment]
Sure, i'll be happy to work on it. It is possible, I'll do it tomorrow morning.
I'm really bad with colors, so any suggestions on what color code should i highlight it with ? 
Should it be higher contrast or lower i mean.

**Comment by PezCoder** [comment]
I tried, not able to do it. hence closing

**Comment by karnh** [comment]
I was able to do this with following on tmux 2.4 with Basic theme -
`set -g status-left "#{?client_prefix,#[fg=yellow]#S#[fg=yellow] ,#S }#[fg=white]Â» #[fg=yellow]#I #[fg=cyan]#P"`
